name = "server-sg"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true
[[routes]]
pattern = "sg1.rinrin.eu.org"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.sg1.rinrin.eu.org"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.sg1.rinrin.eu.org"
custom_domain = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "f21b7162-0004-4f66-95fd-372b6b1dd291"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
